services:
  web:
    build: .
    container_name: studyhall_web
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=studyhall
      - DB_USER=studyhall
      - DB_PASS=change_me
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.11
    container_name: studyhall_db
    environment:
      - MARIADB_ROOT_PASSWORD=supersecret
      - MARIADB_DATABASE=studyhall
      - MARIADB_USER=studyhall
      - MARIADB_PASSWORD=change_me
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -psupersecret || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    container_name: studyhall_adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  dbdata:
